### ISSUE TITLE
Incompatibility between CLI 2.14.0 and maven 3.5.3

### ISSUE THREAD

**Issue by gregoryboue** [jfrog/jfrog-cli#1483]
**Describe the bug**

Since CLI 2.14.0 if i execute the following command for my maven build with maven 3.5.3 : `jf mvn install` I have the following error (complete stacktrace in attachment) : 
```
main] [1;34mINFO[m org.apache.maven.cli.event.ExecutionEventLogger - Scanning for projects...
 [main] [1;34mINFO[m org.jfrog.build.extractor.maven.BuildInfoRecorder - Initializing Artifactory Build-Info Recording
 [main] [1;31mERROR[m org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionStarted() listener has failed: 
 [1;31mjava.lang.NoSuchMethodError[m: [1;31morg.apache.commons.lang3.StringUtils.firstNonBlank([Ljava/lang/CharSequence;)Ljava/lang/CharSequence;[m
     [1mat[m org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveCoreProperties ([1mBuildInfoModelPropertyResolver.java:123[m)
     [1mat[m org.jfrog.build.extractor.maven.BuildInfoModelPropertyResolver.resolveProperties ([1mBuildInfoModelPropertyResolver.java:36
```
[error.log](https://github.com/jfrog/jfrog-cli/files/8314906/error.log)

**To Reproduce**

-> Launch the following commands in a maven project, with maven 3.5.3 on path and with a jfrog cli (2.14.0) configured to uses Artifactory platform (7.25.6) :
-> jf mvn-config ....
-> jf mvn install --build-name mybuild --build-number 1

**Expected behavior**

That my maven artifact are build and published to artifactory

**Versions**

- JFrog CLI version: 2.14.0
- JFrog CLI operating system: Linux (Docker: maven:3.5.3-openjdk-8 image)
- Artifactory Version: 7.25.6

**Additional context**

It seems that the mvn build info extractor is broken since 2.36.0 version with maven 3.5.3, it's ok with maven 3.6.3

**Comment by c-koell** [comment]
We see the same exception.

**Comment by yahavi** [comment]
Thanks for reporting this issue, @gregoryboue & @c-koell!
We created https://github.com/jfrog/build-info/pull/633 to handle it. The fix is expected to be included in the next JFrog CLI release.
We'll keep you updated.

**Comment by yahavi** [comment]
@c-koell,
JFrog CLI 2.14.2 includes a fix for this issue.
Feel free to use it - we'd appreciate your feedback on that.
